#!/bin/bash

# Instructions

# "start looking ..."

# Create a file look, which will look for and show, in the current directory and its sub-folders:

# everything that starts with an a or,

# all the files ending with a z or,

# all files starting with z and ending with a!.

find . \( -name "a*" -o -name "*z" -o -name "z*a!" \)